export const homeInfo = [{ title:'汽车',
    data: [{
        "docid": "0In7RImv",
        "url": "https:\/\/www.yidianzixun.com\/article\/0In7RImv?s=caijing&appid=s3rd_caijing",
        "share_url": "https:\/\/www.yidianzixun.com\/article\/0In7RImv?s=caijing&appid=s3rd_caijing&yd_share=1",
        "date": "2018-04-13 09:19:08",
        "title": "汉兰达慌了，今年这些新款大7座SUV，个个实力派！",
        "images": ["http:\/\/i1.go2yd.com\/corpimage.php?url=0In7RI0w1O&type=_180x120&source=caijing"],
        "source": "车榜",
        "ctype": "news",
        "summary": "随着二胎政策开放，7座SUV被越来越多家庭纳入考虑范围。在合资中大型SUV中，论标杆非汉兰达莫属，几乎所有上市同级别新车总要拿汉兰达来批判一番，但就销量来说，它还没遇到真正的对手，但今年即将上市的几款新SUV，可能真的要对其造成威胁了。",
        "media_pic": "http:\/\/si1.go2yd.com\/get-image\/067cUtSMfQW",
        "media_name": "车榜",
        "category": ["汽车"]
    }, {
        "docid": "0In4JYoI",
        "url": "https:\/\/www.yidianzixun.com\/article\/0In4JYoI?s=caijing&appid=s3rd_caijing",
        "share_url": "https:\/\/www.yidianzixun.com\/article\/0In4JYoI?s=caijing&appid=s3rd_caijing&yd_share=1",
        "date": "2018-04-13 00:00:00",
        "title": "奔驰拼了！北京车展带来37款车 3款全球首发",
        "images": ["http:\/\/i1.go2yd.com\/corpimage.php?url=0In4JY0WLJ&type=_180x120&source=caijing", "http:\/\/i1.go2yd.com\/corpimage.php?url=0In4JYKvsX&type=_180x120&source=caijing", "http:\/\/i1.go2yd.com\/corpimage.php?url=0In4JYJhsV&type=_180x120&source=caijing"],
        "source": "盖世汽车网",
        "ctype": "news",
        "summary": "再有十多天，2018北京国际车展即将盛大开幕。想必各大车企早已“摩拳擦掌”，准备在这两年一度的汽车盛宴中将旗下最新作品公之于众，以夺得更多关注。其中，德系豪华汽车品牌梅赛德斯-奔驰自然不会“落空”，将携旗下奔驰、AMG、迈巴赫以及smart四品牌强势出战。",
        "category": ["汽车"]
    }, {
        "docid": "0ImzolZ7",
        "url": "https:\/\/www.yidianzixun.com\/article\/0ImzolZ7?s=caijing&appid=s3rd_caijing",
        "share_url": "https:\/\/www.yidianzixun.com\/article\/0ImzolZ7?s=caijing&appid=s3rd_caijing&yd_share=1",
        "date": "2018-04-13 00:15:34",
        "title": "最美新车确认过眼神 这就是对的车",
        "images": ["http:\/\/i1.go2yd.com\/corpimage.php?url=0Imzol8L4u&type=_180x120&source=caijing", "http:\/\/i1.go2yd.com\/corpimage.php?url=0ImzolVgzC&type=_180x120&source=caijing", "http:\/\/i1.go2yd.com\/corpimage.php?url=0ImzolxQnb&type=_180x120&source=caijing"],
        "source": "爱卡汽车",
        "ctype": "news",
        "summary": "一年之计在于春，于是众多厂商都选择在3月份推出品牌的重磅车型。而日内瓦和纽约车展也均在3月召开，更是造成了重磅车型扎堆儿上市的局面，想要在这其中搏出位那就必须先有个好颜值。废话不多说，下面我们就来为大家盘点一下3月那些值得我们细细品味的车型吧！",
        "media_pic": "http:\/\/si1.go2yd.com\/get-image\/067NLnwaaR6",
        "media_name": "爱卡汽车",
        "category": ["汽车"]
    }, {
        "docid": "0In0erqe",
        "url": "https:\/\/www.yidianzixun.com\/article\/0In0erqe?s=caijing&appid=s3rd_caijing",
        "share_url": "https:\/\/www.yidianzixun.com\/article\/0In0erqe?s=caijing&appid=s3rd_caijing&yd_share=1",
        "date": "2018-04-13 00:48:30",
        "title": "电动车将让石油走向末路？BP：完全错误！",
        "images": ["http:\/\/i1.go2yd.com\/corpimage.php?url=0In0erwsjk&type=_180x120&source=caijing"],
        "source": "财经十一人",
        "ctype": "news",
        "summary": "BP指出，汽车需求并非主要石油需求，汽车之外，石油需求依然旺盛并将保持增长。到2040年，石油、天然气、煤炭和非化石能源将各满足世界能源需求的四分之一左右",
        "media_pic": "http:\/\/si1.go2yd.com\/get-image\/0BoswXoCxOa",
        "media_name": "财经十一人",
        "category": ["财经"]
    }, {
        "docid": "0In5hLeO",
        "url": "https:\/\/www.yidianzixun.com\/article\/0In5hLeO?s=caijing&appid=s3rd_caijing",
        "share_url": "https:\/\/www.yidianzixun.com\/article\/0In5hLeO?s=caijing&appid=s3rd_caijing&yd_share=1",
        "date": "2018-04-13 08:47:46",
        "title": "全家自驾游的首选 20万级别合资主流七座SUV车型推荐",
        "images": ["http:\/\/i1.go2yd.com\/corpimage.php?url=0In5hLLFkV&type=_180x120&source=caijing"],
        "source": "汽车简报",
        "ctype": "news",
        "summary": "随着我国二胎政策的全面放开，越来越多的家庭开始选择购买7座SUV车型，多数汽车厂家开始选择在这一细分市场投入更多全新的产品，以提高产品竞争力，从侧面突破SUV市场的壁垒。",
        "media_pic": "http:\/\/si1.go2yd.com\/get-image\/0ADdvjb9LfM",
        "media_name": "汽车简报",
        "category": ["汽车"]
    }, {
        "docid": "V_01Yn9LkZ",
        "url": "https:\/\/www.yidianzixun.com\/article\/V_01Yn9LkZ?s=caijing&appid=s3rd_caijing",
        "share_url": "https:\/\/www.yidianzixun.com\/article\/V_01Yn9LkZ?s=caijing&appid=s3rd_caijing&yd_share=1",
        "date": "2018-04-13 09:23:30",
        "title": "这样的路口撞车，谁要负责？交警给出的答案惊呆车主！",
        "images": ["http:\/\/i1.go2yd.com\/corpimage.php?url=V_01Yn9LpoFV&type=_180x120&source=caijing"],
        "source": "汽车洋葱圈",
        "ctype": "video",
        "summary": "这样的路口撞车，谁要负责？交警给出的答案惊呆车主！\n简介：每天开车途中遇到大大小小路口无数，但你可知道像这样没有红绿灯的路口，一旦撞车，谁负全责？",
        "media_pic": "http:\/\/static.yidianzixun.com\/media\/fa51895389bf8d82a4f8f0bbb2d9b23e.jpg",
        "media_name": "汽车洋葱圈",
        "duration": 124,
        "category": ["汽车"]
    }, {
        "docid": "0In8gMzl",
        "url": "https:\/\/www.yidianzixun.com\/article\/0In8gMzl?s=caijing&appid=s3rd_caijing",
        "share_url": "https:\/\/www.yidianzixun.com\/article\/0In8gMzl?s=caijing&appid=s3rd_caijing&yd_share=1",
        "date": "2018-04-13 09:45:35",
        "title": "阿特兹同款底盘，爱信6AT变速箱，这就是自主研发的红旗H5？",
        "images": ["http:\/\/i1.go2yd.com\/corpimage.php?url=0In8gMn6JU&type=_180x120&source=caijing", "http:\/\/i1.go2yd.com\/corpimage.php?url=0In8gM3EiV&type=_180x120&source=caijing", "http:\/\/i1.go2yd.com\/corpimage.php?url=0In8gM70gy&type=_180x120&source=caijing"],
        "source": "车域无疆",
        "ctype": "news",
        "summary": "然而，最近疆哥通过乘联会的数据得知，2018年2月红旗H7销量仅为214辆，在一汽红旗销量中占比100.00%（整个品牌全部销量！！！），在中大型车销量中排名第10位。",
        "media_pic": "http:\/\/static.yidianzixun.com\/media\/3eba56c0198129b219a0fcf03129fc5d.jpg",
        "media_name": "车域无疆",
        "category": ["汽车"]
    }, {
        "docid": "0In8F7jc",
        "url": "https:\/\/www.yidianzixun.com\/article\/0In8F7jc?s=caijing&appid=s3rd_caijing",
        "share_url": "https:\/\/www.yidianzixun.com\/article\/0In8F7jc?s=caijing&appid=s3rd_caijing&yd_share=1",
        "date": "2018-04-13 09:44:42",
        "title": "众泰SUV领衔，名爵、吉利等大波新车4月来袭！",
        "images": ["http:\/\/i1.go2yd.com\/corpimage.php?url=0In8F7FHuZ&type=_180x120&source=caijing", "http:\/\/i1.go2yd.com\/corpimage.php?url=0In8F7Fofk&type=_180x120&source=caijing", "http:\/\/i1.go2yd.com\/corpimage.php?url=0In8F7EYS9&type=_180x120&source=caijing"],
        "source": "汽车之家",
        "ctype": "news",
        "summary": "盼望着盼望着，我们终于迎来了温暖的春天，天朗气清，惠风和畅，万物复苏，一片生机。而在如火如荼的汽车市场，我们也将在4月迎来众多全新车型，话不多说一起来看！",
        "media_pic": "http:\/\/si1.go2yd.com\/get-image\/06jZS9BTQRc",
        "media_name": "汽车之家",
        "category": ["汽车"]
    }, {
        "docid": "0In6Ew7T",
        "url": "https:\/\/www.yidianzixun.com\/article\/0In6Ew7T?s=caijing&appid=s3rd_caijing",
        "share_url": "https:\/\/www.yidianzixun.com\/article\/0In6Ew7T?s=caijing&appid=s3rd_caijing&yd_share=1",
        "date": "2018-04-13 09:05:34",
        "title": "30岁顾家男人首选！这几台大空间SUV，开出去巨体面！",
        "images": ["http:\/\/i1.go2yd.com\/corpimage.php?url=0In6EwZvTh&type=_180x120&source=caijing", "http:\/\/i1.go2yd.com\/corpimage.php?url=0In6EwqXfG&type=_180x120&source=caijing", "http:\/\/i1.go2yd.com\/corpimage.php?url=0In6EwRcs1&type=_180x120&source=caijing"],
        "source": "有车以后",
        "ctype": "news",
        "summary": "常言道，三十而立，到了这个年龄段的人除了处于事业上升期，也逐渐组建了自己的家庭并迎来自己的小可爱，这时候一辆更体面并且更拥有更佳乘坐空间的车型自然成为他们的首选。今天砖叔给大家推荐4款SUV，它们特别适合30岁左右的的消费者，当然这些车的价格也都在30万左右。",
        "media_pic": "http:\/\/si1.go2yd.com\/get-image\/0FKO8WyglxA",
        "media_name": "有车以后",
        "category": ["汽车"]
    }, {
        "docid": "0In3hcSf",
        "url": "https:\/\/www.yidianzixun.com\/article\/0In3hcSf?s=caijing&appid=s3rd_caijing",
        "share_url": "https:\/\/www.yidianzixun.com\/article\/0In3hcSf?s=caijing&appid=s3rd_caijing&yd_share=1",
        "date": "2018-04-13 07:44:49",
        "title": "首次曝光  销量比奥迪Q5和奔驰GLC“多3倍”的豪华SUV是谁",
        "images": ["http:\/\/i1.go2yd.com\/corpimage.php?url=0In3hct9Cb&type=_180x120&source=caijing"],
        "source": "白希文",
        "ctype": "news",
        "summary": "豪华SUV你脑子里有哪些热销车？奥迪Q5?、奔驰GLC，这两款都是月销量破万的车型，而宝马X3由于是进口车的缘故，2017年月销量仅仅4000多台。其他如沃尔沃XC60、凯迪拉克XT5、雷克萨斯NX等同级别豪华SUV，月销量都在3000台以下。那么这次试驾的月",
        "media_pic": "http:\/\/si1.go2yd.com\/get-image\/0Gp8iDVOJOK",
        "media_name": "白希文",
        "category": ["汽车"]
    }, {
        "docid": "0In41Qv1",
        "url": "https:\/\/www.yidianzixun.com\/article\/0In41Qv1?s=caijing&appid=s3rd_caijing",
        "share_url": "https:\/\/www.yidianzixun.com\/article\/0In41Qv1?s=caijing&appid=s3rd_caijing&yd_share=1",
        "date": "2018-04-13 07:30:00",
        "title": "16.98万起，又一全新硬派SUV上市，豪车平台而来！",
        "images": ["http:\/\/i1.go2yd.com\/corpimage.php?url=0In41QhuoR&type=_180x120&source=caijing", "http:\/\/i1.go2yd.com\/corpimage.php?url=0In41Q6l0j&type=_180x120&source=caijing", "http:\/\/i1.go2yd.com\/corpimage.php?url=0In41QkJ47&type=_180x120&source=caijing"],
        "source": "一起去SUV",
        "ctype": "news",
        "summary": "作为帕拉丁的继承者，TERRA途达在不久前刚刚亮相，该车基于之前日产皮卡纳瓦拉的平台打造，同样的平台下还诞生过奔驰X级和雷诺Alaskan；途达使用了非承载式车身，搭载分时四驱系统，定位硬派中型SUV，之后将由郑州日产负责生产，未来将在东风日产和郑州日产两个经",
        "media_pic": "http:\/\/si1.go2yd.com\/get-image\/059P7jdC9A0",
        "media_name": "一起去SUV",
        "category": ["汽车"]
    }, {
        "docid": "0InDP1me",
        "url": "https:\/\/www.yidianzixun.com\/article\/0InDP1me?s=caijing&appid=s3rd_caijing",
        "share_url": "https:\/\/www.yidianzixun.com\/article\/0InDP1me?s=caijing&appid=s3rd_caijing&yd_share=1",
        "date": "2018-04-13 11:24:00",
        "title": "要高性价比？15万左右买这几款紧凑型SUV准没错",
        "images": ["http:\/\/i1.go2yd.com\/corpimage.php?url=0InDP1R0Ox&type=_180x120&source=caijing", "http:\/\/i1.go2yd.com\/corpimage.php?url=0InDP1FQ0M&type=_180x120&source=caijing", "http:\/\/i1.go2yd.com\/corpimage.php?url=0InDP1D5lO&type=_180x120&source=caijing"],
        "source": "SUV大师",
        "ctype": "news",
        "summary": "对于正打算购车的消费者来说，买车确实是个纠结的事情，既要考虑手中的预算，又希望入手自己心仪的车型。前不久有个老铁找到笔者，手里有个15万左右的预算，想买辆SUV家用。这个问题确实很难搞，要知道在这个价位的车型可是相当之多，既有国产又有进口，既有小型又有紧凑型。",
        "media_pic": "http:\/\/s.go2yd.com\/b\/iev5ovmk.jpg",
        "media_name": "SUV大师",
        "category": ["汽车"]
    }, {
        "docid": "0InBApmq",
        "url": "https:\/\/www.yidianzixun.com\/article\/0InBApmq?s=caijing&appid=s3rd_caijing",
        "share_url": "https:\/\/www.yidianzixun.com\/article\/0InBApmq?s=caijing&appid=s3rd_caijing&yd_share=1",
        "date": "2018-04-13 10:37:48",
        "title": "真没骗你！配四轮独立悬挂的合资SUV才卖10万出头",
        "images": ["http:\/\/i1.go2yd.com\/corpimage.php?url=0InBApxEk0&type=_180x120&source=caijing", "http:\/\/i1.go2yd.com\/corpimage.php?url=0InBApcGwQ&type=_180x120&source=caijing", "http:\/\/i1.go2yd.com\/corpimage.php?url=0InBAp112A&type=_180x120&source=caijing"],
        "source": "砖说车",
        "ctype": "news",
        "summary": "对于车辆的悬挂，可能还有些朋友不太了解，也不太清楚选择后独立悬挂究竟对驾驶感觉有多大的提升。后独立悬挂的优点左右车轮各自独立，可以减小车身的倾斜和震动由于车轮各自独立，车轮与地面的附着力更强可以降低发动机的位置，车身重心得到降低可选用刚度小的弹簧，提高汽车的舒",
        "media_pic": "http:\/\/si1.go2yd.com\/get-image\/0H4VVMAfWSW",
        "media_name": "砖说车",
        "category": ["汽车"]
    }, {
        "docid": "0InBC8Qc",
        "url": "https:\/\/www.yidianzixun.com\/article\/0InBC8Qc?s=caijing&appid=s3rd_caijing",
        "share_url": "https:\/\/www.yidianzixun.com\/article\/0InBC8Qc?s=caijing&appid=s3rd_caijing&yd_share=1",
        "date": "2018-04-13 10:35:13",
        "title": "除了帕萨特，这款车开出去也很有面子，而且家用很方便！",
        "images": ["http:\/\/i1.go2yd.com\/corpimage.php?url=0InBC8Trtq&type=_180x120&source=caijing"],
        "source": "车买买",
        "ctype": "news",
        "summary": "随着汽车市场的扩展，可以兼容商务和家用的B级车并不少，而要说起市场份额，日产天籁和大众的帕萨特都占有不少的份额。作为竞争对手两者的竞争也都是比较激烈的，在两者同样宜商宜家的车型中作出选择还是比较难的，今天我们就来比一比。",
        "media_pic": "http:\/\/si1.go2yd.com:8082\/get-image\/02LaMuAxNbc",
        "media_name": "车买买",
        "category": ["汽车"]
    }, {
        "docid": "0InJIWvL",
        "url": "https:\/\/www.yidianzixun.com\/article\/0InJIWvL?s=caijing&appid=s3rd_caijing",
        "share_url": "https:\/\/www.yidianzixun.com\/article\/0InJIWvL?s=caijing&appid=s3rd_caijing&yd_share=1",
        "date": "2018-04-13 14:20:43",
        "title": "国产最新SUV神车，外观让大众宝马汗颜，换个车标能多卖20万！",
        "images": ["http:\/\/i1.go2yd.com\/corpimage.php?url=0InJIW2YGJ&type=_180x120&source=caijing", "http:\/\/i1.go2yd.com\/corpimage.php?url=http://si1.go2yd.com/get-image/0MJZ91a9kzg&type=_180x120&source=caijing", "http:\/\/i1.go2yd.com\/corpimage.php?url=http://si1.go2yd.com/get-image/0MJZ91f24ie&type=_180x120&source=caijing"],
        "source": "张铁绵",
        "ctype": "news",
        "summary": "随着国内几乎全部自主品牌都开始扎堆SUV领域，SUV早已告别蓝海时代，随着哈弗H6倍拉下马，证明后浪总是要把前浪拍在海岸上，目前的市场状况下，再按常规套路出牌很难出人头地，不按套路出牌的宝骏510就是一个很好的例证。而近日东风风光也拿出了一款最新的个性化SUV",
        "media_pic": "http:\/\/si1.go2yd.com:8082\/get-image\/02fIehcX5f6",
        "media_name": "张铁绵",
        "category": ["汽车"]
    }, {
        "docid": "0ImMg4B4",
        "url": "https:\/\/www.yidianzixun.com\/article\/0ImMg4B4?s=caijing&appid=s3rd_caijing",
        "share_url": "https:\/\/www.yidianzixun.com\/article\/0ImMg4B4?s=caijing&appid=s3rd_caijing&yd_share=1",
        "date": "2018-04-12 00:04:00",
        "title": "春季严查北斗导航开始了！山东、河北、安徽等地严查行车记录仪！",
        "images": ["http:\/\/i1.go2yd.com\/corpimage.php?url=0ImMg4lh9L&type=_180x120&source=caijing", "http:\/\/i1.go2yd.com\/corpimage.php?url=0ImMg4egDC&type=_180x120&source=caijing", "http:\/\/i1.go2yd.com\/corpimage.php?url=0ImMg4UFOj&type=_180x120&source=caijing"],
        "source": "自主汽车",
        "ctype": "news",
        "summary": "俗话说，\"春困秋乏夏打盹\"，春季成为了疲劳驾驶的高峰期，为了防止长途司机疲劳驾驶而引发车祸，最近运管严查北斗\/GPS行车记录仪的地方明显增多。",
        "category": ["汽车"]
    }, {
        "docid": "0ImyzaJo",
        "url": "https:\/\/www.yidianzixun.com\/article\/0ImyzaJo?s=caijing&appid=s3rd_caijing",
        "share_url": "https:\/\/www.yidianzixun.com\/article\/0ImyzaJo?s=caijing&appid=s3rd_caijing&yd_share=1",
        "date": "2018-04-12 22:42:48",
        "title": "又一本田豪车陨落，大量停滞在4S店空地停灰，全场12万已成地摊货",
        "images": ["http:\/\/i1.go2yd.com\/corpimage.php?url=0ImyzahZvb&type=_180x120&source=caijing", "http:\/\/i1.go2yd.com\/corpimage.php?url=0Imyzab9lE&type=_180x120&source=caijing", "http:\/\/i1.go2yd.com\/corpimage.php?url=0ImyzaC6vv&type=_180x120&source=caijing"],
        "source": "欣车鉴",
        "ctype": "news",
        "summary": "说道汽车，特别是suv，近年来受关注的程度是相当的高，说句实话suv确实很实用，因为它不仅空间大而且还适合很多崎岖不好的山路，对于大部分来说这就很实在，不像轿车，只能在城市里跑跑。因此在国内的汽车市场上suv的销量是相当的可观的，特别是吉利和哈弗这两个品牌一直",
        "media_pic": "http:\/\/si1.go2yd.com\/get-image\/0LzVISFxp0S",
        "media_name": "欣车鉴",
        "category": ["汽车"]
    }, {
        "docid": "V_01YkVdpN",
        "url": "https:\/\/www.yidianzixun.com\/article\/V_01YkVdpN?s=caijing&appid=s3rd_caijing",
        "share_url": "https:\/\/www.yidianzixun.com\/article\/V_01YkVdpN?s=caijing&appid=s3rd_caijing&yd_share=1",
        "date": "2018-04-12 17:28:39",
        "title": "看到这些车一定要远离至少3米！否则不是人吃亏就是钱吃亏！",
        "images": ["http:\/\/i1.go2yd.com\/corpimage.php?url=V_01YkVd7JYp&type=_180x120&source=caijing"],
        "source": "军武次位面",
        "ctype": "video",
        "summary": "如今汽车的价格不断在下探，买车代步已经是在平常不过的事。虽然有车以后，生活出行上方便了很多。但随着行驶在路上的车辆越来越多，驾驶环境也越来越复杂，隐藏的危险也就越来越多。",
        "media_pic": "http:\/\/si1.go2yd.com\/get-image\/04Qqby8hQjA",
        "media_name": "军武次位面",
        "duration": 201,
        "category": ["社会"]
    }, {
        "docid": "0IlZ9d9K",
        "url": "https:\/\/www.yidianzixun.com\/article\/0IlZ9d9K?s=caijing&appid=s3rd_caijing",
        "share_url": "https:\/\/www.yidianzixun.com\/article\/0IlZ9d9K?s=caijing&appid=s3rd_caijing&yd_share=1",
        "date": "2018-04-10 15:14:16",
        "title": "警惕！发现车上有这个\"记号\"一定要小心！快告诉家人",
        "images": ["http:\/\/i1.go2yd.com\/corpimage.php?url=0IlZ9d846v&type=_180x120&source=caijing", "http:\/\/i1.go2yd.com\/corpimage.php?url=0IlZ9dTpqh&type=_180x120&source=caijing", "http:\/\/i1.go2yd.com\/corpimage.php?url=0IlZ9ddh6W&type=_180x120&source=caijing"],
        "source": "科普中国",
        "ctype": "news",
        "summary": "开车出门前你检查过车门、后车窗、车轮这些小细节么？如果下面说的这几个情况，在你车上发现了，那就要注意啦！很有可能是你的爱车被“盯”上了。",
        "media_pic": "http:\/\/si1.go2yd.com\/get-image\/0Ao3pLNVivg",
        "media_name": "科普中国",
        "category": ["汽车"]
    }]
}]